eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

target:
  name: 이준택

greeting:
  hello: 안녕하세용
