eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

target:
  name: 이준택
